[package]
name = "cargo-nextest"
description = "A next-generation test runner for Rust."
version = "0.9.12"
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://nexte.st"
keywords = ["nextest", "test-runner", "flaky-tests", "junit"]
categories = ["development-tools::cargo-plugins", "development-tools::testing"]
edition = "2021"
rust-version = "1.56"

[dependencies]
camino = "1.0.7"
cfg-if = "1.0.0"
clap = { version = "3.1.8", features = ["derive", "env"] }
# we don't use the tracing support
color-eyre = { version = "0.6.1", default-features = false }
duct = "0.13.5"
enable-ansi-support = "0.1.2"
# we don't use the default formatter so we don't need default features
env_logger = { version = "0.9.0", default-features = false }
guppy = "0.14.1"
log = "0.4.16"
nextest-runner = { version = "0.5.0", path = "../nextest-runner" }
nextest-metadata = { version = "0.3.0", path = "../nextest-metadata" }
owo-colors = { version = "3.3.0", features = ["supports-colors"] }
shellwords = "1.1.0"
supports-color = "1.3.0"
serde_json = "1.0.79"

[dev-dependencies]
cfg-if = "1.0.0"
tempfile = "3.3.0"
regex = "1.5.5"
once_cell = "1.10.0"
