[package]
name = "quick-junit"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"

[dependencies]
chrono = "0.4.19"
indexmap = "1.7.0"
quick-xml = "0.22.0"

[dev-dependencies]
goldenfile = "1.1.0"
owo-colors = "3.1.1"
