[package]
name = "quick-junit"
description = "Serializer for JUnit/XUnit XML"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/diem/diem-devtools"
documentation = "https://docs.rs/quick-junit"
edition = "2021"

[dependencies]
chrono = "0.4.19"
indexmap = "1.8.0"
quick-xml = "0.22.0"

[dev-dependencies]
goldenfile = "1.1.0"
owo-colors = "3.2.0"
