[package]
name = "quick-junit"
description = "Data model and serializer for JUnit/XUnit XML"
version = "0.3.2"
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://docs.rs/quick-junit"
keywords = ["junit", "xunit", "xml", "serializer", "flaky-tests"]
categories = ["encoding", "development-tools"]
edition = "2021"
rust-version = "1.66"

[dependencies]
chrono = "0.4.26"
indexmap = "1.9.3"
quick-xml = "0.28.2"
thiserror = "1.0.40"
uuid = "1.3.4"
nextest-workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
goldenfile = "1.4.5"
owo-colors = "3.5.0"
