[package]
name = "quick-junit"
description = "Data model and serializer for JUnit/XUnit XML"
version = "0.3.0"
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://docs.rs/quick-junit"
keywords = ["junit", "xunit", "xml", "serializer", "flaky-tests"]
categories = ["encoding", "development-tools"]
edition = "2021"
rust-version = "1.62"

[dependencies]
chrono = "0.4.22"
indexmap = "1.9.1"
quick-xml = "0.26.0"
thiserror = "1.0.37"
uuid = "1.2.1"
nextest-workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
goldenfile = "1.4.3"
owo-colors = "3.5.0"
