[package]
name = "nextest-metadata"
version = "0.2.0"
description = "Structured access to nextest machine-readable output."
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://docs.rs/nextest-metadata"
keywords = ["nextest", "test-runner"]
categories = ["development-tools::testing"]
rust-version = "1.54"

[dependencies]
camino = { version = "1.0.7", features = ["serde1"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
