[package]
name = "nextest-metadata"
version = "0.8.0"
description = "Structured access to nextest machine-readable output."
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://docs.rs/nextest-metadata"
keywords = ["nextest", "test-runner"]
categories = ["development-tools::testing"]
rust-version = "1.66"

[dependencies]
camino = { version = "1.1.4", features = ["serde1"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
target-spec = { version = "1.3.1", features = ["summaries"] }
nextest-workspace-hack = { version = "0.1", path = "../workspace-hack" }
smol_str = { version = "0.1.24", features = ["serde"] }

[dev-dependencies]
test-case = "3.0.0"
