[package]
name = "nextest-metadata"
version = "0.9.1"
description = "Structured access to nextest machine-readable output."
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/nextest-rs/nextest"
documentation = "https://docs.rs/nextest-metadata"
keywords = ["nextest", "test-runner"]
categories = ["development-tools::testing"]
rust-version = "1.70"

[dependencies]
camino = { version = "1.1.6", features = ["serde1"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
target-spec = { version = "3.0.1", features = ["custom", "summaries"] }
nextest-workspace-hack = { version = "0.1", path = "../workspace-hack" }
smol_str = { version = "0.2.0", features = ["serde"] }

[dev-dependencies]
test-case = "3.2.1"
